/** Dashboard screen walkthrough. The Dashboard always has data, so most anchors
 * resolve; specific opportunity tiles are described on a tile step. */
import { launchScreenTour, scrollIntoView, type ScreenStep } from '../screenTour';

const STEPS: ScreenStep[] = [
  { element: '.smart-header', title: 'Your Dashboard',
    body: 'The month’s price book in numbers, your own workspace, and the opportunities CELR has found for you, all on one screen. <b>Why it helps:</b> your day starts here.' },
  { element: '.filter-pills', title: 'Focus on one distributor',
    before: () => scrollIntoView('.filter-pills'),
    body: 'These chips re-scope the whole dashboard to one distributor, or all of them at once. <b>Why it helps:</b> see the picture for just the supplier you are working with.' },
  { element: '.section-label', title: 'Three bands',
    before: () => scrollIntoView('.section-label'),
    body: 'The dashboard runs top to bottom in three bands: <b>Key Metrics</b>, <b>My Workspace</b>, then <b>Insights &amp; Opportunities</b>. <b>Why it helps:</b> the numbers, your work, then the deals.' },
  { element: '.kpi-grid', title: 'The month at a glance',
    before: () => scrollIntoView('.kpi-grid'),
    body: 'These cards summarise this edition: total items, active discounts, clearance, price drops and increases, and active RIPs. <b>Why it helps:</b> the shape of the month in one look.' },
  { element: '.kpi-card', title: 'Every card is a shortcut',
    before: () => scrollIntoView('.kpi-card'),
    savings: '💰 Jump straight to the dollars behind the number',
    body: 'Click a card to open that list, already filtered. <b>Active Discounts</b> also shows the total <b>savings pool</b> on the table. <b>Why it helps:</b> from a number to the products behind it in one click.' },
  { element: '.dashboard-tile-grid', title: 'My Workspace',
    before: () => scrollIntoView('.dashboard-tile-grid'),
    body: 'The middle band is your own activity: <b>Favorites</b>, <b>orders in progress</b>, <b>submitted orders</b>, and <b>notes</b>. <b>Why it helps:</b> pick up exactly where you left off.' },
  { element: '.dashboard-tile', title: 'Tiles expand for detail',
    before: () => scrollIntoView('.dashboard-tile'),
    body: 'Each tile shows a count and a quick preview; click it to open the full table in a pop-up without leaving the page. <b>Why it helps:</b> a glance now, the detail when you want it.' },
  { element: '.dashboard-tile-grid:last-of-type', title: 'Insights & Opportunities',
    before: () => scrollIntoView('.dashboard-tile-grid:last-of-type'),
    body: 'The bottom band is the deals CELR surfaces: New Items, Time-Sensitive Deals, Top Discounts, month-over-month Price Changes, and who is cheaper across distributors. <b>Why it helps:</b> the best moves come to you.' },
  { element: '.dashboard-tile-grid:last-of-type .dashboard-tile', title: 'Time-sensitive deals',
    before: () => scrollIntoView('.dashboard-tile-grid:last-of-type'),
    savings: '⏱️ Catch deals before they expire',
    body: 'The <b>Time-Sensitive Deals</b> tile surfaces offers that expire soon or whose price is not available next month. <b>Why it helps:</b> act before they are gone.' },
  { element: '.dashboard-tile-grid:last-of-type .dashboard-tile', title: 'Biggest drops and top discounts',
    before: () => scrollIntoView('.dashboard-tile-grid:last-of-type'),
    savings: '💰 Largest savings per case, ranked',
    body: 'Other tiles rank the <b>biggest price drops</b> and the <b>top discount opportunities</b> this edition, sorted by the savings. <b>Why it helps:</b> the strongest deals float to the top automatically.' },
  { element: '.dashboard-tile-grid:last-of-type .dashboard-tile', title: 'Who is cheaper',
    before: () => scrollIntoView('.dashboard-tile-grid:last-of-type'),
    body: 'The cross-distributor tiles (<b>Allied Cheaper</b>, <b>Fedway Cheaper</b>, <b>OPICI Cheaper</b>) flag the same UPC where one supplier beats another, per bottle. <b>Why it helps:</b> buy from whoever is cheapest, spotted for you.' },
  { element: '.smart-header', title: 'It updates with the data',
    before: () => window.scrollTo({ top: 0, behavior: 'auto' }),
    body: 'Every number and tile reflects the current edition and your distributor filter at the top. <b>Why it helps:</b> the dashboard is always current, never stale.' },
  { element: '.kpi-grid', title: 'That’s the Dashboard',
    before: () => scrollIntoView('.kpi-grid'),
    body: 'Numbers up top, your work in the middle, the best deals below. <b>Why it helps:</b> the whole month, and your next move, on one screen.' },
];

export const launchDashboardTour = (navigate: (p: string) => void) =>
  launchScreenTour(navigate, '/dashboard', '.kpi-grid', STEPS);
